

# 同步与异步

## 同步

### 什么是同步

只有当前任务执行完成，才会进入下一个任务。

### 同步的缺点

注意：所有同步代码只会进入调用栈，同步代码会阻塞主线程的执行，而且会优先与其他非同步代码执行

## 异步

### 什么是异步？

当前执行的代码会进入异步线程处理之后，再由主线程处理回调

### 异步的几种形式，分别的优缺点？

>1.回调函数。解决了同步的问题，但本身存在回调地狱的问题，用try catch捕获异常很麻烦，不能return
>
>2.promise。采用级联代替回调，解决回调地狱，但是promise无法取消，捕获错误需要通过回调函数进行捕获
>
>3.generator。可以控制函数的执行
>
>4.async await。代码清晰，没有回调函数的问题。但在处理相互之间没有依赖的多个异步操作的时候，会导致性能降低，不如用peomise.all



#### 1.回调函数

例如setTimeout/setInterval、ajax、事件回调等

##### 优点：

避免出现任务阻塞（解决了同步的问题）

##### 缺点：

**回调地狱，不能用 try catch 捕获错误，不能 return**

##### 什么是回调地狱

由于嵌套过多，耦合度太高。所以整体调试困难，只能把每一个嵌套函数当作一个单元来调试



#### 2.promise

##### 优点：

采用链式调用的方式代替回调函数的嵌套，解决了回调地狱的问题：

promise是对回调函数的一种封装。将对回调函数的调用修改成一种消息发送，把对结果的处理剥离出去，交给后续的对象处理。

resolve和reject可以理解为发送信息的函数。一方面，将Promise的状态由pending改为resolved和reject。另一方面，生成一个新的Promise，并将数据作为参数传递出去。

本质是为了把层层嵌套异步回调代码，回调地狱 callback hell，转变为串行的链式调用。

参考：

[JavaScript：Promise的基础套路](https://www.jianshu.com/p/ce4a34ead4b5)



##### 缺点：

1.promise过程中无法取消（状态中只有pending，reject，resolve，没有所谓的 cancel 状态。cancel 的加入会带来更多的状态问题，并不适合 Promise 这一模式来处理）

2.**错误需要通过回调函数来捕获**(reject函数)

参考：

[为什么说promise不能取消是一个缺点](https://m.imooc.com/wenda/detail/473806)

#### 3.Generator

##### 特点：

能够控制函数执行

```js
function *fetch() {
    yield ajax('XXX1', () => {})
    yield ajax('XXX2', () => {})
    yield ajax('XXX3', () => {})
}
let it = fetch()
let result1 = it.next()
let result2 = it.next()
let result3 = it.next()
```

#### 4.async await

##### 优点：

解决回调地狱的同时，保证了代码的清晰，不用像Promise写一堆then链

##### 缺点：

await 将异步代码改造成同步代码，会阻塞主线程

```js
async function test() {
  // 以下代码没有依赖性的话，完全可以使用 Promise.all 的方式
  // 如果有依赖性的话，其实就是解决回调地狱的例子了
  await fetch('XXX1')
  await fetch('XXX2')
  await fetch('XXX3')
}
```

注意点：

- await后面如果接promise，返回的是promise执行的结果；
- 如果是常量，则返回常量；
- 如果是同步函数，返回的是同步函数的执行结果（await不会起作用，相当于没加await）

#### 5.async await和promise，generator三者之间的区别

##### 冻结变量对象的问题

- `await` 是 `generator` 加上 `Promise`的语法糖，且内部实现了自动执行generator
- Generator 函数，它所执行产生的上下文环境，一旦遇到`yield`命令，就会暂时退出堆栈，但是并不消失，**里面的所有变量和对象会冻结在当前状态。**等到对它执行`next`命令时，这个上下文环境又会重新加入调用栈，冻结的变量和对象恢复执行。

- promise也拥有这种特性


promise就不会对上下文的变量对象进行冻结

###### 参考：[Generator 与上下文](https://es6.ruanyifeng.com/#docs/generator)



##### 举几个例子：

###### 栗子1

```js
let a = 0
let b = async () => {
    console.log(11)
  a = a + await 10;
  console.log('2', a) // -> '2' 10
}
b()
a++
console.log('1', a) // -> '1' 1
```

对于以上代码你可能会有疑惑，让我来解释下原因

- 首先函数 `b` 先执行，在执行到 `await 10` 之前变量 `a` 还是 0，因为 `await` 内部实现了 `generator` ，**`generator` 会保留堆栈中东西，所以这时候 `a = 0` 被保存了下来**
- 因为 `await` 是异步操作，后来的表达式不返回 `Promise` 的话，就会包装成 `Promise.reslove(返回值)`，然后会去执行函数外的同步代码
- 同步代码执行完毕后开始执行异步代码，将保存下来的值拿出来使用，这时候 `a = 0 + 10`





###### 栗子2

对比下面promise，promise就不会对上下文的变量进行冻结

```js
let a = 0;
let b = () => {
    new Promise((resolve) => {
        resolve(10);
    })
    .then(value => {
        a = a + value;
        console.log('qqq', a);
    });
}
b();
a++;
console.log('www', a);

// www 1
// qqq 11
```

参考：

[JS异步解决方案的发展历程以及优缺点 #29](https://github.com/sisterAn/blog/issues/29)





## promise详解

### promise.all

#### 介绍下 Promise.all 使用、原理实现及错误处理

#### promise的使用场景

**如果多个异步操作没有依赖性而使用 await 会导致性能上的降低，不如用Promise.all**

#### promise的使用方法

Promise.all()接受一个由promise任务组成的数组，可以同时处理多个promise任务。

1. 当所有的任务都执行完成后，Promise.all()返回resolve，
2. 但当有一个失败(reject)，则返回失败的信息，即使其他promise执行成功，也会返回失败。

参考：

[第 80 题：介绍下 Promise.all 使用、原理实现及错误处理](https://github.com/Advanced-Frontend/Daily-Interview-Question/issues/130#)#130



